mod server;
mod server_auth;
mod state;

/// Create custom server, wire it to the autogenerated router,
/// and pass it to the web server.
#[tokio::main]
async fn main() {
    env_logger::init();

    let addr = "127.0.0.1:8000";

    server::create(addr).await;
}
